### ISSUE TITLE
HTML Create Deck Modal Window

### ISSUE THREAD

**Issue by sunny-script** [Danr55/Indexd#10]
When initially clicked on, should show several fields for user to add inputs to: 
Deck Name: 
Question:
Answer: 

Then, should include two options at bottom of modal window that allow the user to either: 
Close and complete the deck
Add another question/answer pairing to the deck

If the  user chooses to close and complete the deck, the modal window closes. 
If the user chooses to add another question/answer pairing to the deck, they will see:

Question: 
Answer: 
Close and complete 
Add another question/answer pairing

**Comment by Danr55** [comment]
Modal and answer question completed
