### ISSUE TITLE
Randomized Index Card

### ISSUE THREAD

**Issue by sunny-script** [Danr55/Indexd#11]
Once a user creates a deck, they should be able to click on a deck from the nav. 
Once they do, a random index card should appear in the center of the page and display a question. 
Once the user clicks on the index card, user should see the answer to the question. 
Once the user clicks again, a randomized index card shows the question.
The cycle repeats for as long as the user has index cards / question and answer pairings

**Comment by Danr55** [comment]
Index cards are displaying at random and answer is hidden.  button to reveal answer is working and next question displays another question at random
